### ISSUE TITLE
LSP formatting deletes characters when `set expandtab`

### ISSUE THREAD

**Issue by svanharmelen** [svanharmelen/dotfiles#6]
Hi @psiho 👋🏻

Sorry to reach out to you like this, but I'm a little bit stuck and noticed you found yourself fixing the exact same issue a while ago... So I wondered if you ever solved it and, if so, if you could share the solution?

I'm talking about this issue: https://neovim.discourse.group/t/lsp-formatting-deletes-characters-when-set-expandtab/2465

I did try to search both and online and on Github, but I failed to find any other references to this problem other then your post. So thought to just give it a try and reach out before opening a new issue.

Thanks for your time!
Sander

**Comment by psiho** [comment]
I answered in that thread, in case somebody else is wondering. Although, it's not too helpful unfortunately.

**Comment by svanharmelen** [comment]
No problem, thanks for your time! I'll respond there as well and will close this issue here...
